"""Cram-mode schedule generator.

The cognitive-science research report explicitly recommends multi-pass
retrieval over a 24-hour pre-exam window: at least two later retrievals
beat a single exposure, sleep between passes consolidates declarative
memory (Walker/Stickgold), and a pre-sleep weak-set pass exploits
overnight consolidation (Gais 2006).

Anki schedules cards but doesn't tell you *when* to study. This module
emits a markdown checklist with concrete time blocks anchored to your
exam datetime. It's deliberately a printout, not an interactive UI —
v0.1 keeps complexity out of the runtime.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta


@dataclass(frozen=True)
class Pass:
    """One retrieval pass in the 24-hour cram schedule."""

    label: str
    offset_before_exam: timedelta
    duration_minutes: int
    description: str
    activity: str


# Six-pass template grounded in the spacing/sleep evidence summarized in
# the research report. Offsets are anchored to the exam start time.
_PASSES: tuple[Pass, ...] = (
    Pass(
        label="A — Diagnostic",
        offset_before_exam=timedelta(hours=24),
        duration_minutes=45,
        description="Read the high-yield summary in guide.md. Mark every section you can't explain in 30 seconds.",
        activity="Open guide.md → speak each section's main point aloud → flag weak sections.",
    ),
    Pass(
        label="B — Failed-recall sweep",
        offset_before_exam=timedelta(hours=23),
        duration_minutes=20,
        description="Filtered Anki deck on flagged sections only. Reschedule OFF.",
        activity='Anki: Custom Study → "Cards in random order" → tag:high_yield AND tag:<weak_topic>.',
    ),
    Pass(
        label="C — Deep dive on weak topic 1",
        offset_before_exam=timedelta(hours=20),
        duration_minutes=60,
        description="Single-topic block: read source, build a comparison table or flowchart from memory, verify against guide.",
        activity="Pick the weakest section. Write its summary blind. Diff against guide.md.",
    ),
    Pass(
        label="D — Mixed retrieval",
        offset_before_exam=timedelta(hours=14),
        duration_minutes=40,
        description="Interleaved practice across all topics. This is where retention compounds.",
        activity='Anki filtered deck: "exam::<name>" with rescheduling OFF, sibling burying ON. ~150 cards.',
    ),
    Pass(
        label="E — Pre-sleep weak set",
        offset_before_exam=timedelta(hours=10),
        duration_minutes=25,
        description="Final weak-card pass within 60–90 min of sleep. Exploits overnight consolidation.",
        activity="Anki: only cards you got wrong today. Speak each answer aloud. Then sleep.",
    ),
    Pass(
        label="F — Morning final pass",
        offset_before_exam=timedelta(hours=2),
        duration_minutes=40,
        description="Light review only — no new material. Skim mnemonic page + 20 quick cards.",
        activity="Read high_yield_summary section. Single coffee 60–90 min before exam. No QBank.",
    ),
)


def generate_cram_plan(
    exam_name: str,
    exam_datetime: datetime,
    *,
    guide_path: str = "./out/guide.md",
    deck_path: str = "./out/deck.apkg",
    language: str = "en",
) -> str:
    """Render a markdown cram plan anchored to a specific exam datetime."""
    if language == "pt-BR":
        return _render_pt(exam_name, exam_datetime, guide_path, deck_path)
    return _render_en(exam_name, exam_datetime, guide_path, deck_path)


def _fmt(dt: datetime) -> str:
    return dt.strftime("%a %b %d · %H:%M")


def _render_en(exam_name: str, exam_dt: datetime, guide: str, deck: str) -> str:
    lines: list[str] = []
    lines.append(f"# Cram plan — {exam_name}")
    lines.append("")
    lines.append(f"*Exam: {_fmt(exam_dt)} · Generated by sinapze*")
    lines.append("")
    lines.append("Why six passes: at least two retrievals beat one exposure (Cepeda 2008), sleep consolidates declarative memory (Walker), pre-sleep review exploits that consolidation window (Gais 2006). Strict retrieval practice — no rereading without testing.")
    lines.append("")
    lines.append(f"**Inputs:** [`{guide}`]({guide}) · [`{deck}`]({deck})")
    lines.append("")
    lines.append("---")
    lines.append("")
    for p in _PASSES:
        when = exam_dt - p.offset_before_exam
        lines.append(f"## Pass {p.label}")
        lines.append(f"**Start:** {_fmt(when)} · **Duration:** {p.duration_minutes} min")
        lines.append("")
        lines.append(p.description)
        lines.append("")
        lines.append(f"- [ ] {p.activity}")
        lines.append("- [ ] Mark cards you got wrong with the `weak` Anki tag.")
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("## Hard rules")
    lines.append("")
    lines.append("- **No new card generation in the last 24h.** Run `sinapze cards` before pass A and stop.")
    lines.append("- **Anki rescheduling stays OFF in filtered decks** so cramming doesn't corrupt long-term intervals.")
    lines.append("- **Protect 7–8 hours of sleep.** All-nighter cognitive impairment ≈ 0.05–0.10 BAC (Scullin 2018). Sleep beats any extra study you'd buy.")
    lines.append("- **One coffee, 60–90 min before the exam.** Caffeine peaks at 30–60 min.")
    lines.append("- **No QBank in the last 60 minutes.** Avoid pre-exam anxiety cascade.")
    return "\n".join(lines)


def _render_pt(exam_name: str, exam_dt: datetime, guide: str, deck: str) -> str:
    lines: list[str] = []
    lines.append(f"# Plano de revisão — {exam_name}")
    lines.append("")
    lines.append(f"*Prova: {_fmt(exam_dt)} · Gerado por sinapze*")
    lines.append("")
    lines.append("Por que seis passagens: pelo menos duas recuperações superam uma exposição única (Cepeda 2008); o sono consolida memória declarativa (Walker); a revisão pré-sono aproveita essa janela de consolidação (Gais 2006). Prática de recuperação rigorosa — não reler sem testar.")
    lines.append("")
    lines.append(f"**Insumos:** [`{guide}`]({guide}) · [`{deck}`]({deck})")
    lines.append("")
    lines.append("---")
    lines.append("")
    pt_descriptions = {
        "A — Diagnostic": ("A — Diagnóstico", "Leia o resumo de alto rendimento em guide.md. Marque cada seção que você não consegue explicar em 30 segundos.", "Abra guide.md → fale o ponto principal de cada seção em voz alta → marque seções fracas."),
        "B — Failed-recall sweep": ("B — Varredura de falhas", "Deck filtrado do Anki apenas nas seções marcadas. Reagendamento DESLIGADO.", 'Anki: Estudo Personalizado → "Cartões em ordem aleatória" → tag:high_yield AND tag:<topico_fraco>.'),
        "C — Deep dive on weak topic 1": ("C — Aprofundamento no tópico fraco 1", "Bloco de tópico único: leia a fonte, construa uma tabela ou fluxograma de memória, confira contra o guia.", "Escolha a seção mais fraca. Escreva o resumo dela às cegas. Compare com guide.md."),
        "D — Mixed retrieval": ("D — Recuperação mista", "Prática intercalada entre tópicos. É onde a retenção se compõe.", 'Deck filtrado do Anki: "exam::<nome>" com reagendamento DESLIGADO, irmãos ocultos LIGADO. ~150 cartões.'),
        "E — Pre-sleep weak set": ("E — Conjunto fraco pré-sono", "Última passagem nos cartões fracos 60–90 min antes de dormir. Aproveita a consolidação noturna.", "Anki: apenas cartões errados hoje. Fale cada resposta em voz alta. Depois durma."),
        "F — Morning final pass": ("F — Passagem final matinal", "Apenas revisão leve — sem material novo. Folheie a página de mnemônicos + 20 cartões rápidos.", "Leia a seção high_yield_summary. Um café 60–90 min antes da prova. Sem QBank."),
    }
    for p in _PASSES:
        when = exam_dt - p.offset_before_exam
        label_pt, desc_pt, act_pt = pt_descriptions[p.label]
        lines.append(f"## Passagem {label_pt}")
        lines.append(f"**Início:** {_fmt(when)} · **Duração:** {p.duration_minutes} min")
        lines.append("")
        lines.append(desc_pt)
        lines.append("")
        lines.append(f"- [ ] {act_pt}")
        lines.append("- [ ] Marque os cartões errados com a tag Anki `weak`.")
        lines.append("")
        lines.append("---")
        lines.append("")
    lines.append("## Regras inegociáveis")
    lines.append("")
    lines.append("- **Sem gerar cartões novos nas últimas 24h.** Rode `sinapze cards` antes da passagem A e pare.")
    lines.append("- **Reagendamento do Anki DESLIGADO em decks filtrados** — cramming não pode corromper intervalos de longo prazo.")
    lines.append("- **Proteja 7–8 horas de sono.** Privação aguda equivale a 0,05–0,10 g/L de álcool (Scullin 2018).")
    lines.append("- **Um café, 60–90 min antes da prova.** Cafeína atinge pico em 30–60 min.")
    lines.append("- **Sem QBank nos últimos 60 minutos.** Evite cascata de ansiedade pré-prova.")
    return "\n".join(lines)
